In [41]:
from tensorflow import keras
from tensorflow.keras import layers
import pandas as pd
import numpy as np
import matplotlib as mp
import tensorflow as tf
from sklearn.model_selection import train_test_split
from tensorflow.keras.callbacks import EarlyStopping

In [42]:
train_data = pd.read_csv("data/train.csv")
test_data = pd.read_csv("data/test.csv")

In [43]:
y = train_data['SalePrice']

In [44]:
train_data = train_data.drop(columns=['SalePrice'])
# train_data.head()
# test_data.head()

In [45]:
print(train_data.shape, test_data.shape)

(1460, 80) (1459, 80)

In [46]:
total_data = pd.concat([train_data, test_data])

In [47]:
print(total_data.shape)

(2919, 80)

In [48]:
total_data = total_data.dropna(axis='columns')

In [49]:
print(total_data.shape)

(2919, 46)

In [50]:
train_data.head(100)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,2,2008,WD,Normal
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,5,2007,WD,Normal
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,9,2008,WD,Normal
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,12,2008,WD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,60,RL,NaN,9765,Pave,NaN,IR2,Lvl,AllPub,...,0,0,NaN,NaN,Shed,480,4,2009,WD,Normal
96,97,20,RL,78.0,10264,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,8,2006,WD,Normal
97,98,20,RL,73.0,10921,Pave,NaN,Reg,HLS,AllPub,...,0,0,NaN,NaN,NaN,0,5,2007,WD,Normal
98,99,30,RL,85.0,10625,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,Shed,400,5,2010,COD,Abnorml
99,100,20,RL,77.0,9320,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,Shed,400,1,2010,WD,Normal

In [51]:
total_data = pd.get_dummies(total_data, drop_first=True)
total_data.head()

,Id,MSSubClass,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,1stFlrSF,2ndFlrSF,LowQualFinSF,...,HeatingQC_Po,HeatingQC_TA,CentralAir_Y,PavedDrive_P,PavedDrive_Y,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,1,60,8450,7,5,2003,2003,856,854,0,...,0,0,1,0,1,0,0,0,1,0
1,2,20,9600,6,8,1976,1976,1262,0,0,...,0,0,1,0,1,0,0,0,1,0
2,3,60,11250,7,5,2001,2002,920,866,0,...,0,0,1,0,1,0,0,0,1,0
3,4,70,9550,7,5,1915,1970,961,756,0,...,0,0,1,0,1,0,0,0,0,0
4,5,60,14260,8,5,2000,2000,1145,1053,0,...,0,0,1,0,1,0,0,0,1,0